/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Todo_todo.flow
 * @generated SignedSource<<ff51102ace0273a2616236954da94c93>>
 * @flow
 */

'use strict';

export type Todo_todo = {
  id: string;
  complete: boolean;
  text: string;
};
