/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Todo_todo.flow
 * @generated SignedSource<<535f2f77aeb69a7de631b7e0b1b0e488>>
 * @flow
 */

'use strict';

export type Todo_todo = {
  complete: boolean;
  id: string;
  text: string;
};
