/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule TodoApp_viewer.graphql
 * @generated SignedSource<<d23ea5e16d8bbf61cea9efdb2e7c51e4>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type TodoApp_viewer = {
  id: string;
  allTodoes: TodoApp_viewer_allTodoes;
};

export type TodoApp_viewer_allTodoes_edges_node = {
  id: string;
  complete: boolean;
};

export type TodoApp_viewer_allTodoes_edges = {
  node: TodoApp_viewer_allTodoes_edges_node;
};

export type TodoApp_viewer_allTodoes = {
  edges?: ?Array<?TodoApp_viewer_allTodoes_edges>;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "TodoApp_viewer",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "id",
      "storageKey": null
    },
    {
      "kind": "LinkedField",
      "alias": null,
      "args": [
        {
          "kind": "Literal",
          "name": "first",
          "value": 1000,
          "type": "Int"
        }
      ],
      "concreteType": "TodoConnection",
      "name": "allTodoes",
      "plural": false,
      "selections": [
        {
          "kind": "LinkedField",
          "alias": null,
          "args": null,
          "concreteType": "TodoEdge",
          "name": "edges",
          "plural": true,
          "selections": [
            {
              "kind": "LinkedField",
              "alias": null,
              "args": null,
              "concreteType": "Todo",
              "name": "node",
              "plural": false,
              "selections": [
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "id",
                  "storageKey": null
                },
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "complete",
                  "storageKey": null
                }
              ],
              "storageKey": null
            }
          ],
          "storageKey": null
        }
      ],
      "storageKey": "allTodoes{\"first\":1000}"
    },
    {
      "kind": "FragmentSpread",
      "name": "TodoListFooter_viewer",
      "args": null
    },
    {
      "kind": "FragmentSpread",
      "name": "TodoList_viewer",
      "args": null
    }
  ],
  "type": "Viewer"
};

module.exports = fragment;
