/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule TodoListFooter_viewer.graphql
 * @generated SignedSource<<179781eef4e99b291cd59dbf12ebb0f5>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type TodoListFooter_viewer = {
  allTodoes: TodoListFooter_viewer_allTodoes;
};

export type TodoListFooter_viewer_allTodoes_edges_node = {
  id: string;
  complete: boolean;
};

export type TodoListFooter_viewer_allTodoes_edges = {
  node: TodoListFooter_viewer_allTodoes_edges_node;
};

export type TodoListFooter_viewer_allTodoes = {
  edges?: ?Array<?TodoListFooter_viewer_allTodoes_edges>;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "TodoListFooter_viewer",
  "selections": [
    {
      "kind": "LinkedField",
      "alias": null,
      "args": [
        {
          "kind": "Literal",
          "name": "first",
          "value": 1000,
          "type": "Int"
        }
      ],
      "concreteType": "TodoConnection",
      "name": "allTodoes",
      "plural": false,
      "selections": [
        {
          "kind": "LinkedField",
          "alias": null,
          "args": null,
          "concreteType": "TodoEdge",
          "name": "edges",
          "plural": true,
          "selections": [
            {
              "kind": "LinkedField",
              "alias": null,
              "args": null,
              "concreteType": "Todo",
              "name": "node",
              "plural": false,
              "selections": [
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "id",
                  "storageKey": null
                },
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "complete",
                  "storageKey": null
                }
              ],
              "storageKey": null
            }
          ],
          "storageKey": null
        }
      ],
      "storageKey": "allTodoes{\"first\":1000}"
    }
  ],
  "type": "Viewer"
};

module.exports = fragment;
