/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Todo_viewer.flow
 * @generated SignedSource<<f27f0078ea86ec8bdd573cba309ae350>>
 * @flow
 */

'use strict';

export type Todo_viewer = {
  id: string;
};
